### PR TITLE
Bump compatibility requirements for HDF5

### PR DESCRIPTION
**Pull request by ablaom**
The old version is causing problems in MLJ, for example.

 This pull request also **bumps the version for Julia to 1.3** because the new versions of HDF5 require Julia 1.3.

@dfdx

### CODE REVIEW

**Comment by dfdx** [comment]
Thanks for the recent PRs! 

Since we are bumping the minimal Julia version, I think we need to update the version of the NaiveBayes package itself and release it, as well as update Travis testing matrix. I'll do it myself once Travis finishes the currently running checks.

**Comment by ablaom** [comment]
FYI Free travis is ending (public non-paying repos have a quota which will run out - you seem to be good for now). Instead you can use a github action (what most julia devs are doing):

https://discourse.julialang.org/t/easy-workflow-file-for-setting-up-github-actions-ci-for-your-julia-package/49765

It's pretty straightforward - just install one file on your repo.

**Comment by dfdx** [comment]
Oh, I thought Travis just unifies their domains 0_o Thanks for the tip, I will follow your suggestion tomorrow as I get to my laptop!

**Comment by dfdx** [comment]
@ablaom Version 0.5.0 has been tagged and released.

**Pull request merged**
