### PR TITLE
Add Project.toml

### PR DESCRIPTION
**Pull request by ablaom**
I've been running into package conflicts when using NaiveBayes.jl with other ML packages and julia versions less than 1.2. I think adding a Project.toml would help. 

@dfdx Be good to tag a new patch after this. Nowadays, this is done through [JuliaHub](https://juliahub.com/ui/Home)

### CODE REVIEW

**Comment by OkonSamuel** [comment]
@ablaom julia v1.5 tests are failing and i think you have to add random package to extras to tests to fix this.

**Comment by ablaom** [comment]
@dfdx Okay, passing tests now.

**Comment by dfdx** [comment]
Thanks a lot! I will tag a new version now.

**Comment by dfdx** [comment]
Here we go
https://github.com/JuliaRegistries/General/pull/22133

**Comment by ablaom** [comment]
Great! Thanks for the prompt response.

**Pull request merged**
